### ISSUE TITLE
hangs on trying to download album

### ISSUE THREAD

**Issue by buzzbo** [96AA48/gmplayer#10]
Not sure what's up. My internet connection is fine.

    /home/pi$ chmod 600 .gmplayerrc
    [pi@raspberrypi]
    /home/pi$ gmp -a Echolyn
    Looking up requested album \
    [0] Echolyn - Echolyn
    [1] I Heard You Listening - Echolyn
    [2] Cowboy Poems Free - Echolyn
    [3] A Little Nonsense: Now and Then - echolyn
    [4] Suffocating the Bloom - echolyn
    [5] as the world - echolyn
    [6] The End is Beautiful - echolyn
    [7] mei - echolyn
    [8] Orange-ish Blue - echolyn / Brett Kull
    [9] This is My Halo - echolyn / Ray Weston
    [10] finneus gauge: one inch of the fall - echolyn / Chris Buzby
    What album do you want to play? #7

    Downloading echolyn - mei
    [                                                                          ] 0%

It hangs indefinitely...at least 20 minutes with no change until I `^c`.

**Comment by buzzbo** [comment]
Actually it eventually downloaded the file and showed progress at the very end. The above is a one-song album. 

But when I try it with a multi-song album, I get a (throw?) error. Four songs partially downloaded before this:

    events.js:72
            throw er; // Unhandled 'error' event
                  ^
    Error: socket hang up
        at createHangUpError (http.js:1472:15)
        at CleartextStream.socketCloseListener (http.js:1522:23)
        at CleartextStream.emit (events.js:117:20)
        at tls.js:691:10
        at process._tickCallback (node.js:419:13)

**Comment by 96AA48** [comment]
Seems like an odd issue. I implemented the progressbar feature because of a crappy internet connection when I was on vacation. The architecture of the script that downloads the files is asynchronous, so therefor might make the first few seconds to minutes with `0%` on the progressbar seem weird. 
  
I also know that some albums behave in a weird way, I've got a GUI project coming up for Google Play where I ran into the same issue without much of a fix.
  
As for the `socket hang up` issue, I don't really know what the issue is. If you can check if the file has been fully downloaded would make a difference, otherwise it just might be your internet connection.

**Comment by buzzbo** [comment]
The `socket hang` issue appears to happen when I download an album--more than one song. I've tried several times and get impartial downloads each time. I can download individual songs but not an album of several tracks. Perhaps it's related to downloading multiple files at once.

**Comment by 96AA48** [comment]
Could be, can you send your ~/.gmplayerrc file and mention the search term that you're using as well as the selected album? I could try to recreate the bug.

**Comment by buzzbo** [comment]
You mean you want my gmplayerc with my google credentials?

Incidentally I the previous attempts were on raspberry pi (raspbian), and now I tried this on another system (linux mint) and I got a new error:

    What album do you want to play? #0

    Downloading Metallica - Garage, Inc.
    [                                                                          ] 0%
    events.js:72
            throw er; // Unhandled 'error' event
                  ^
    Error: read ECONNRESET
        at errnoException (net.js:901:11)
        at TCP.onread (net.js:556:19)

**Comment by buzzbo** [comment]
Popping in again. I am having mixed success. It seems that I get some errors when I try an album, but when I delete the album folder in `Music/gmplayer`, then run it again `gmp -a [pattern]` and select the same album, it then works. Inexplicable.

**Comment by 96AA48** [comment]
Yeah I've been running into the same issue as well. Seems there is some underlying issue with downloading songs from the album asynchronously or something. You could clone the repo, `npm link` it and try out some fixes if you want.
