### ISSUE TITLE
Corrupt file for one (long) song

### ISSUE THREAD

**Issue by motevets** [96AA48/gmplayer#14]
When I download the album _Narrow Stairs_ by Death Cab for Cutie using `gmplayer`, the second track _I Will Possess Your Heart_ comes out corrupt (all the rest are fine.)  I.E. it plays, but has peculiar skips throughout the whole track.  I tried manually downloading the track using the same URL `playmusic` provides to `gmplayer`, and it plays fine using `mplayer`.  The only thing I can think  of that distinguishes this track from other tracks is the length/size.

Even weirder is that the file downloaded by `gmplayer` is *larger* (31,104 bytes) than the one I downloaded manually (19,764 bytes).

So my questions for you, @96AA48, are:

1. Does the same thing happen for you?
2. Do you have any idea what might be causing this?

**Comment by motevets** [comment]
Side notes:

1. I did try downloading it multiple times and the issue remains, but the pattern of the skips changes.
1. It may not be skipping but instead just have the bytes in the wrong order.
1. Eventually the song stops and `mplayer` reports something like

      mpg123 decoding failed: No stream opened. (code 24)
      A:  68.7 (01:08.6) of 788.5 (13:08.4)  1.4%

**Comment by 96AA48** [comment]
I'm currently running your provided steps to see if I'm running into the same problems. As for now, I downloaded the album using `gmplayer` and [looked at the directory and file sizes](https://i.imgur.com/DPWhe2T.png). 

For me, _I Will Possess Your Heart_ doesn't come out corrupted thus far and doesn't have a differing file size. So no, this doesn't happen to me for some reason. I can't imagine what would cause this, but I see that you're [researching](https://github.com/motevets/gmplayer/commit/9f54e3bcf00f0837605aefe922457face4007a6a) that yourself.

This doesn't mean that this isn't an issue, only that as far as I can see, I can't help you.
The only thing I can think of is maybe the environment that you're using and the version of gmplayer.

**Comment by motevets** [comment]
Ha, I didn't mean for this to become polluted with all my pushes. :(

When you downloaded _I Will Possess Your Heart_ did you do so downloading the whole album or just a single track?  I.e. `gmp -s "I Will Possess Your Heart"` or `gmp -a "Narrow Stairs"`?

Other pertinent information maybe be that I'm working/testing off of the current master from your fork, and:
```shell
motevets@stevetom ~ $ uname -r
3.19.0-58-generic
motevets@stevetom ~ $ lsb_release -a
No LSB modules are available.
Distributor ID: LinuxMint
Description:    Linux Mint 17.3 Rosa
Release:        17.3
Codename:       rosa
motevets@stevetom ~ $ node -v
v5.10.0
```
I just created a pull request, #15.  For me, it seemed to fix the issue.

**Comment by 96AA48** [comment]
Hey @motevets, I downloaded the album fully in order to try it out. It seems that doing it again, after some time did cause the bug to happen. It seems to be related to how `ffmpeg` is being called from `ffmetadata` from what I can see, since most of the inconsistencies show up when `ffmpeg` throws an error.

Your fix would allow for a more synchronous approach that `ffmpeg` likes a bit more. I'll merge the pull request and release the patch to npm. 

Thanks for your contribution. Also you've got me listening to _Narrow Stairs_, which is a nice addition to my day!

**Comment by motevets** [comment]
Thanks!  If I get a chance, I'll try to do get `gmp -a` to start playing after the first song has downloaded which I think would be a nice feature.

Glad you're enjoying _Narrow Stairs_. I'm a big Death Cab for Cuties fan.  I'm a little ashamed to admin that *Bixby Canyon Bridge* may have played a role in my decision to move to the San Francisco Bay Area.
