### ISSUE TITLE
Error google credentials

### ISSUE THREAD

**Issue by buzzbo** [96AA48/gmplayer#16]
I just updated with `npm install gmplayer -g` and now I get this error, though I haven't changed my `.gmplayerrc` file nor my google authentication settings.

```
ERROR: Error: Unable to create oauth tokenError: You must provide either an email address and password, or a token

ERROR: Error: Unable to create oauth tokenError: 403 error from server
```
I reading [this thread](https://github.com/jamon/playmusic/issues/27), which didn't help. I don't have 2-step authentication going.

**Comment by buzzbo** [comment]
Just downgraded to 0.3.1 which works again. I'm not much of a developer so I can't tell what is causing this error.

**Comment by 96AA48** [comment]
Yeah the new version of `gmplayer` includes an encrypted password storage on your `.gmplayerrc`. Try to update to the latest version and delete your `.gmplayerrc`. Then instead of filling in your password and email just lookup any song with `gmp` and it will prompt for giving your email adress and password. The password encryption will be automatic.

**Comment by buzzbo** [comment]
I see. I did just that and it is working again. I'll go ahead and close this although it *is* unexpected behavior. Maybe first run should detect an older version of `.gmplayerrc`. Just a thought.

Though I want to say I really enjoy using this software since I have the Google Play All Access. I love being able to play my music on Linux devices!

**Comment by 96AA48** [comment]
I'm glad to hear you enjoy the application. You make a good suggestion to check for older versions of `gmplayer`, but not every version has a changed `.gmplayerrc`. When I decide to make another change to how the application interacts with `.gmplayerrc` I'll be sure to add the feature you proposed. For now I'll just make an FAQ on the Github page linking to this issue. 

Thank you for your time and feel free to come back here if you find any other issues with the application. Also feel free to make a pull request for any new features that you've got in mind.

**Comment by buzzbo** [comment]
Well I know a *little* javascript but nothing on node. Maybe I'll poke around some time!
