### ISSUE TITLE
2 factor

### ISSUE THREAD

**Issue by malac0da13** [96AA48/gmplayer#17]
Doesn't seem to work with 2 factor authentication.

**Comment by 96AA48** [comment]
This functionality would depend on an upstream project called [playmusic](http://github.com/jamon/playmusic), the maintainer hasn't had much time making this possible.
[However, there is an issue opened there right now discussing the possibility of OAuth / Two-factor auth](https://github.com/jamon/playmusic/issues/67).

Feel free to contribute to that project or this with a Pull request!

Happy coding!
