### ISSUE TITLE
ERROR: Error: Unable to get stream urlError: 404 error from server

### ISSUE THREAD

**Issue by Multipixelone** [96AA48/gmplayer#21]
Whenever I try to download some albums or songs I get the error:

ERROR: Error: Unable to get stream urlError: 404 error from server

**Comment by spencermathews** [comment]
Has this been fixed? I just tried gmplayer and got this same error.

**Comment by buzzbo** [comment]
Why did you close this? I get this same error when I'm trying to get a radio station.
