### ISSUE TITLE
Store tracks in folders per album/artist

### ISSUE THREAD

**Issue by Widdershin** [96AA48/gmplayer#3]
Currently, all tracks are stored in the root level music directory.

This will quickly become messy, especially with the introduction of album/playlist support.

I think we should create a directory in the music root with a name of `gmplayer`, and then store all downloaded tracks in there in the format of `~/Music/gmplayer/<artist>/<album>/<tracknumber> - <title>.mp3`.

Note: I plan on implementing this, but I figured I would make an issue first to see what you think :smile:

**Comment by 96AA48** [comment]
Yeah we could defintely do that. Feel free to implement it. We could also add the downloaded files in .gmplayerrc as a small JSON database to make an offline shuffle function or something. Either that or like a dotfile in each folder of every album or something. We could even add options in the .gmplayerrc on how the user wants the sorting done.

Also a small note, there are albums out there that have multiple artists in one album, which might make sorting by artist a bit hard/weird.

**Comment by Digikid13** [comment]
I would prefer it to be sorted by genre, if that information is available.

**Comment by 96AA48** [comment]
We could also make this an config variable in `~/.gmplayerrc` probably.
