### ISSUE TITLE
-d option doesn't work.

### ISSUE THREAD

**Issue by Digikid13** [96AA48/gmplayer#8]
It just exists when you try to use it.

Seems to be that cli.main() is missing options.downloadonly, when I tried adding it in awhile back it didn't work.

**Comment by 96AA48** [comment]
Yeah, that seems about right. I actually added that switch but forgot to implement it. I'll look into it today and push the changes.

**Comment by 96AA48** [comment]
My apologies for the time it took in order to fix this. It was a simple solution, it's just that I haven't found the time to program lately. Pull the master branch and let me know if it works!

**Comment by Digikid13** [comment]
No big deal, it seems you forgot to implement it in the cli.main() function though, so it just falls through cause there are no valid options.

**Comment by 96AA48** [comment]
You're right that it's not implemented in the `cli.main()` function. However, the switch is being used later in the progress of downloading albums and songs. If you want to download a song, just search like you normally would, but this time with the `-d` switch as well.

**Comment by Digikid13** [comment]
I'm confused, so you want something like `gmp -s -d <songname>`? Cause `gmp -d <songname>` doesn't do anything.

**Comment by Digikid13** [comment]
Well usually it's `<command> <options> <parameters>`, so having it as `<cmd> <opt> <params> <other opt>` is a bit confusing.

**Comment by 96AA48** [comment]
You could always use `gmp -d -s <whatever you're looking for>` if I'm correct. The thing is, if we implement `gmp -d <query>` like it is, then the script has no way of knowing if the user wants albums or songs.
