### ISSUE TITLE
-s fails to download song

### ISSUE THREAD

**Issue by Digikid13** [96AA48/gmplayer#9]
I tried using the latest update and it seems that (for me at least) after I select a song to download it just freezes and doesn't seem to do anything.

![freeze?](https://cloud.githubusercontent.com/assets/2277583/11005898/7924793a-8475-11e5-9631-9db5bdbd586e.png)

**Comment by 96AA48** [comment]
I'm aware of the issue. It has bugged me before with a very specific song as well. The issue seems to be the naming scheme as far as I can tell. I'll look into it.

**Comment by 96AA48** [comment]
I've researched the issue, but as soon as I tried to fix it, it seemed to fixed itself. No idea why. Are you still having the issue?

**Comment by Digikid13** [comment]
I found out the cause of the issue, it's because the custom naming can return invalid characters [\/:*?"<>|] (#windows). It was using the {genre} for my folders and google seemed to return "Dance|Electronic", since there are 2 genres.

**Comment by 96AA48** [comment]
I've looked into the issue again, and it seems to be working right now. I'd like to test it with your custom naming scheme. Would you mind sending me your .gplayerrc file?
